import type { Clause } from '@en18031/shared';

export const STANDARD_VERSION = 'EN18031:2019';

export const SEED_CLAUSES: Clause[] = [
  {
    clauseId: '5.1',
    standardVersion: STANDARD_VERSION,
    chapter: '5.1',
    title: '身份认证机制',
    description: '设备应对用户进行身份认证，默认账户必须强制修改密码，口令应满足复杂度与过期策略。',
    level: 'L1',
    testingMethod: '检查默认口令、密码策略、登录失败锁定。',
    defaultSeverity: 'high',
    tags: ['身份认证'],
  },
  {
    clauseId: '5.1-1',
    standardVersion: STANDARD_VERSION,
    chapter: '5.1',
    title: '默认账户必须强制修改密码',
    description: '出厂默认账户与口令在首次使用时必须强制修改，不得允许默认口令持续可用。',
    level: 'L1',
    testingMethod: '使用厂商默认口令尝试登录，应被拒绝或强制修改。',
    defaultSeverity: 'high',
    parentId: '5.1',
    tags: ['身份认证', '默认口令'],
  },
  {
    clauseId: '5.1-2',
    standardVersion: STANDARD_VERSION,
    chapter: '5.1',
    title: '口令策略必须包含复杂度、长度、过期要求',
    description: '口令应至少 8 位、含大小写数字符号，并设置有效期与历史口令限制。',
    level: 'L2',
    testingMethod: '审查口令策略配置，尝试设置弱口令应被拒绝。',
    defaultSeverity: 'middle',
    parentId: '5.1',
    tags: ['身份认证', '口令策略'],
  },
  {
    clauseId: '5.1-3',
    standardVersion: STANDARD_VERSION,
    chapter: '5.1',
    title: '登录失败次数锁定机制',
    description: '连续登录失败达到阈值后应锁定账户或引入验证码/延迟。',
    level: 'L2',
    testingMethod: '连续输错密码，验证账户锁定或限流生效。',
    defaultSeverity: 'middle',
    parentId: '5.1',
    tags: ['身份认证', '暴力破解防护'],
  },
  {
    clauseId: '5.2',
    standardVersion: STANDARD_VERSION,
    title: '权限分离',
    chapter: '5.2',
    description: '系统应区分管理员与普通用户权限，防止越权操作。',
    level: 'L2',
    defaultSeverity: 'middle',
    tags: ['授权'],
  },
  {
    clauseId: '5.2-1',
    parentId: '5.2',
    standardVersion: STANDARD_VERSION,
    chapter: '5.2',
    title: '权限分离至少区分管理员与普通用户',
    description: '不同角色的访问权限应分离，普通用户不能执行管理操作。',
    level: 'L2',
    testingMethod: '以普通用户登录尝试管理操作，应被拒绝。',
    defaultSeverity: 'middle',
    tags: ['授权', '权限分离'],
  },
  {
    clauseId: '5.3',
    standardVersion: STANDARD_VERSION,
    chapter: '5.3',
    title: '网络通信安全',
    description: '不必要的网络服务应禁用，管理协议应使用加密通道，服务发现协议不得对外网暴露。',
    level: 'L1',
    testingMethod: '端口扫描与服务识别，对照业务需求核查端口。',
    defaultSeverity: 'high',
    tags: ['网络通信'],
  },
  {
    clauseId: '5.3-1',
    standardVersion: STANDARD_VERSION,
    chapter: '5.3',
    title: '所有不必要网络服务必须禁用',
    description: '设备应仅运行业务必需的网络服务，所有非必要端口与服务必须关闭。',
    level: 'L1',
    testingMethod: '对设备进行全端口扫描，逐一核实开放端口是否为业务必需。',
    defaultSeverity: 'middle',
    parentId: '5.3',
    tags: ['网络通信', '端口合规'],
  },
  {
    clauseId: '5.3-2',
    standardVersion: STANDARD_VERSION,
    chapter: '5.3',
    title: '明文管理协议 Telnet/HTTP 不得开放',
    description: 'Telnet(23)、HTTP(80) 等明文管理协议不得用于设备管理，防止凭据与通信内容被窃听。',
    level: 'L1',
    testingMethod: 'nmap 扫描 23、80 端口并尝试连接，确认未开放或重定向到加密协议。',
    defaultSeverity: 'high',
    parentId: '5.3',
    tags: ['网络通信', '明文协议'],
  },
  {
    clauseId: '5.3-3',
    standardVersion: STANDARD_VERSION,
    chapter: '5.3',
    title: '必须使用加密管理协议 SSH/HTTPS',
    description: '远程管理必须使用 SSH(22) 或 HTTPS(443) 等加密协议。',
    level: 'L1',
    testingMethod: '确认至少存在 SSH 或 HTTPS 管理通道且可正常使用。',
    defaultSeverity: 'middle',
    parentId: '5.3',
    tags: ['网络通信', '加密管理'],
  },
  {
    clauseId: '5.3-4',
    standardVersion: STANDARD_VERSION,
    chapter: '5.3',
    title: '默认口令必须修改',
    description: '网络服务相关的默认账户/口令必须修改，不得使用厂商默认凭据。',
    level: 'L1',
    testingMethod: '对开放的管理服务尝试默认凭据，应登录失败。',
    defaultSeverity: 'high',
    parentId: '5.3',
    tags: ['网络通信', '默认口令'],
  },
  {
    clauseId: '5.3-5',
    standardVersion: STANDARD_VERSION,
    chapter: '5.3',
    title: 'UPnP/SSDP/MDNS 等服务不得对外网暴露',
    description: '服务发现协议(1900/UDP SSDP、5353/UDP mDNS 等)仅可在内网使用，不得向公网暴露。',
    level: 'L2',
    testingMethod: '扫描 1900/5353 等端口，核查服务是否对外网可达。',
    defaultSeverity: 'middle',
    parentId: '5.3',
    tags: ['网络通信', '服务发现'],
  },
  {
    clauseId: '5.4',
    standardVersion: STANDARD_VERSION,
    chapter: '5.4',
    title: '通信加密',
    description: '通信应使用经过安全配置的加密协议与套件，证书应合法有效。',
    level: 'L2',
    testingMethod: 'SSL/TLS 扫描、证书核查、固件升级包完整性校验。',
    defaultSeverity: 'high',
    tags: ['加密传输'],
  },
  {
    clauseId: '5.4-1',
    standardVersion: STANDARD_VERSION,
    chapter: '5.4',
    title: '通信加密套件不得使用已知弱算法',
    description: '禁用 SSLv3/TLS1.0/TLS1.1 及 RC4/DES/3DES/EXPORT/NULL/anon 等弱套件。',
    level: 'L2',
    testingMethod: 'nmap ssl-enum-ciphers 或 openssl 核查协议与套件。',
    defaultSeverity: 'high',
    parentId: '5.4',
    tags: ['加密传输', '弱加密'],
  },
  {
    clauseId: '5.4-2',
    standardVersion: STANDARD_VERSION,
    chapter: '5.4',
    title: 'TLS 证书必须合法有效且正确配置',
    description: '证书应在有效期内、域名匹配、由受信任 CA 签发，不得使用过期/自签名证书用于生产。',
    level: 'L2',
    testingMethod: 'openssl s_client 检查证书有效期、颁发者、域名匹配。',
    defaultSeverity: 'middle',
    parentId: '5.4',
    tags: ['加密传输', '证书'],
  },
  {
    clauseId: '5.4-3',
    standardVersion: STANDARD_VERSION,
    chapter: '5.4',
    title: '固件升级过程必须完整性校验和签名验证',
    description: '固件升级包必须进行完整性校验与数字签名验证，防止被篡改。',
    level: 'L3',
    testingMethod: '审查升级流程，尝试刷入篡改/未签名固件应被拒绝。',
    defaultSeverity: 'high',
    parentId: '5.4',
    tags: ['加密传输', '固件升级'],
  },
  {
    clauseId: '5.5',
    standardVersion: STANDARD_VERSION,
    chapter: '5.5',
    title: '固件与敏感数据安全',
    description: '固件中不得存在硬编码密钥/凭据，应具备防逆向保护，调试接口默认关闭。',
    level: 'L2',
    testingMethod: 'binwalk 解包、strings 扫描密钥、核查 JTAG/UART。',
    defaultSeverity: 'high',
    tags: ['固件安全'],
  },
  {
    clauseId: '5.5-1',
    standardVersion: STANDARD_VERSION,
    chapter: '5.5',
    title: '固件中不得存在硬编码密钥或凭据',
    description: '固件镜像中不得包含硬编码的密码、API Key、私钥、云平台凭据。',
    level: 'L2',
    testingMethod: '解包固件，strings 搜索 password/secret/private key 等模式。',
    defaultSeverity: 'high',
    parentId: '5.5',
    tags: ['固件安全', '硬编码凭据'],
  },
  {
    clauseId: '5.5-2',
    standardVersion: STANDARD_VERSION,
    chapter: '5.5',
    title: '固件必须有防止逆向读取的保护措施',
    description: '固件应加密、签名或启用读保护，防止敏感信息被直接提取。',
    level: 'L3',
    testingMethod: '尝试解包读取文件系统，验证加密/读保护生效。',
    defaultSeverity: 'middle',
    parentId: '5.5',
    tags: ['固件安全', '防逆向'],
  },
  {
    clauseId: '5.5-3',
    standardVersion: STANDARD_VERSION,
    chapter: '5.5',
    title: '调试接口 JTAG/UART 默认关闭',
    description: 'JTAG/UART 等硬件调试接口在量产固件中应关闭或受认证保护。',
    level: 'L3',
    testingMethod: '检查串口/JTAG 是否输出调试 shell 或可读写内存。',
    defaultSeverity: 'middle',
    parentId: '5.5',
    tags: ['固件安全', '调试接口'],
  },
];
